from showyourwork2.plugins import staging

stage = staging.ZenodoStage("stage", config.get("restore", False), "stage.json")

rule a:
    output:
        stage("output/a.txt")
    run:
        raise ValueError("this should not be executed")

include:
    staging.snakefile()
