from showyourwork.plugins import staging

stage = staging.NoOpStage("stage", config.get("restore", False))

rule a:
    output:
        stage("output/a.txt")
    run:
        raise ValueError("this should not be executed")

include:
    staging.snakefile()
