repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v4.4.0"
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude_types: [json, binary]
        exclude: "^tests/projects/"
      - id: check-yaml
  - repo: https://github.com/psf/black
    rev: "23.1.0"
    hooks:
      - id: black-jupyter
        exclude: "^tests/projects/"
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.0.277"
    hooks:
      - id: ruff
        exclude: "^docs/|^tests/projects/"
        args: [--fix, --exit-non-zero-on-fix]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: "v1.0.0"
    hooks:
      - id: mypy
        exclude: "^docs/|^tests/projects/"
        additional_dependencies: ["types-PyYAML", "types-requests"]
