from showyourwork.plugins import staging

stage = staging.ZenodoStage(
    "stage",
    config.get("restore", False),
    "stage.json",
    url=config["zenodo_mock_url"],
)

rule a:
    output:
        stage("output/a.txt")
    shell:
        """
        mkdir -p output
        echo "test" > {output}
        """

include:
    staging.snakefile()
