from showyourwork.plugins import staging

stage = staging.NoOpStage("stage", config.get("restore", False))

rule a:
    output:
        stage("output/a.txt")
    shell:
        """
        mkdir -p output
        echo "test" > {output}
        """

include:
    staging.snakefile()
