from showyourwork2.dag import trace_dag_dependencies
from showyourwork2.config.models import Config
from pydantic import create_model

config = Config.model_validate({"config_version": 2})
trace_dag_dependencies(config)

checkpoint check_deps:
    input:
        "dynamic_deps.txt"
    output:
        touch("checkpoint.flag")

def get_dependencies(*_):
    checkpoints.check_deps.get()
    with open("dynamic_deps.txt") as f:
        return f.read().splitlines()

rule deps:
    input:
        get_dependencies
    output:
        "dependencies.json"
    run:
        import json
        blob = {str(k): list(sorted(map(str, v))) for k, v in config._dependency_tree.items()}
        with open(output[0], "w") as f:
            json.dump(blob, f, indent=2, sort_keys=True)

rule gen_dep:
    input:
        "dep0"
    output:
        "dep1.txt"
    shell:
        """
        cat {input} > {output}
        """

rule dynamic_deps:
    output:
        "dynamic_deps.txt"
    shell:
        """
        echo "dep1.txt" > dynamic_deps.txt
        """
