name: tests

on:
  push:
    branches:
      - main
      - staging*
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
        include:
          - platform: macos-latest
            python-version: "3.10"
          # - platform: windows-latest
          #   python-version: "3.10"

    runs-on: ${{ matrix.platform }}
    name: unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            mamba

      - name: Cache test conda environments
        uses: actions/cache@v3
        with:
          path: .test/conda
          key: ${{ runner.os }}-${{ matrix.python-version }}-conda-${{ hashFiles('**/environment.yml') }}-${{ hashFiles('**/envs/*.yml') }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.python-version }}-conda-

      - name: Install showyourwork
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[test]"

      - name: Run tests
        run: python -m pytest -v tests
