name: tests

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  workflow_dispatch:

jobs:
  tests:
    defaults:
      run:
        shell: bash -el {0}

    strategy:
      fail-fast: false
      matrix:
        platform:
          - ubuntu-latest
        python-version:
          - "3.9"
          - "3.10"
          - "3.11"
        include:
          - platform: macos-latest
            python-version: "3.10"
          # - platform: windows-latest
          #   python-version: "3.10"

    runs-on: ${{ matrix.platform }}
    name: unit tests
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Set up Mamba
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: test-env
          create-args: >-
            python=${{ matrix.python-version }}
            mamba

      - name: Install showyourwork
        run: |
          python -m pip install -U pip
          python -m pip install -e ".[test]"

      - name: Run tests
        run: python -m pytest -v tests

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v4
        name: Install Python
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install -U pip
          python -m pip install -U build twine
      - name: Build the distribution
        run: python -m build .
      - name: Check the distribution
        run: python -m twine check --strict dist/*
      - uses: actions/upload-artifact@v3
        with:
          path: dist/*

  publish:
    environment:
      name: pypi
      url: https://pypi.org/p/showyourwork2
    permissions:
      id-token: write
    needs: [tests, build]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.8.6
